---
- name: "🆕 Breaking-Change"
  color: ee0701
  description: "A breaking change for existing users."
- name: "🪲 Bug"
  color: ee0701
  description: "Inconsistencies or issues which will cause a problem for users or implementors."
- name: "📄 Documentation"
  color: 0052cc
  description: "Solely about the documentation of the project."
- name: "📈 Enhancement"
  color: 1d76db
  description: "Enhancement of the code, not introducing new features."
- name: "🛠️ Refactor"
  color: 1d76db
  description: "Improvement of existing code, not introducing new features."
- name: "〽️ Performance"
  color: 1d76db
  description: "Improving performance, not introducing new features."
- name: "🆕 New-Feature"
  color: 0e8a16
  description: "New features or options."
- name: "🔧 Maintenance"
  color: 2af79e
  description: "Generic maintenance tasks."
- name: "Ⓜ️ Dependencies"
  color: 1d76db
  description: "Upgrade or downgrade of project dependencies."


- name: "✳️ In-Progress"
  color: fbca04
  description: "Issue is currently being resolved by a developer."
- name: "❌ Won't-Fix"
  color: "ffffff"
  description: "This will not be worked on"
- name: "😵 Stale"
  color: fef2c0
  description: "There has not been activity on this issue or PR for quite some time."
- name: "☠️ No-Stale"
  color: fef2c0
  description: "This issue or PR is exempted from the stable bot."

- name: "🔒 Security"
  color: ee0701
  description: "Marks a security issue that needs to be resolved ASAP."
- name: "⁉ Incomplete"
  color: fef2c0
  description: "Marks a PR or issue that is missing information."
- name: "⛔ Invalid"
  color: fef2c0
  description: "Marks a PR or issue that is missing information."

- name: "🫂 Beginner-Friendly"
  color: 0e8a16
  description: "Good first issue for people wanting to contribute to the project."
- name: "⚠️ Help-Wanted"
  color: 0e8a16
  description: "We need some extra helping hands or expertise in order to resolve this."

# additional issue types
- name: "🧪 Experimental"
  color: "bfdadc"
  description: "Experimental purpose issues"
- name: "☢️ Priority-Critical"
  color: ee0701
  description: "This should be dealt with ASAP. Not fixing this issue would be a serious error."
- name: "⚡ Priority-High"
  color: b60205
  description: "After critical issues are fixed, these should be dealt with before any further issues."
- name: "🔥 Priority-Medium"
  color: 0e8a16
  description: "This issue may be useful, and needs some attention."
- name: "❄️ Priority-Low"
  color: e4ea8a
  description: "Nice addition, maybe... someday..."
- name: '🧑‍🤝‍🧑 Duplicate'
  color: cfd3d7
  description: 'This issue or pull request already exists'  


# Release
- name: "🚀 Release"
  color: "bada55"
  description: "Release related issues"
- name: "🔟 Major"
  color: b60205
  description: "This PR causes a major version bump in the version number."
- name: "🔢 Minor"
  color: 0e8a16
  description: "This PR causes a minor version bump in the version number."

# Time
- name: "⏳ Time: Long"
  color: "333333"
  description: "The issue takes about a week"
- name: "⌚ Time: Middle"
  color: "999999"
  description: "The issue takes a few days"
- name: "⏲️ Time: Short"
  color: "eeeeee"
  description: "The issue takes several hours"
